<?php echo $this->doctype(); ?>

<html lang="pl">
    <head>
	<meta charset="utf-8">
        <?php echo $this->headTitle('Rabatem '. $this->translate('Panel Administratora'))->setSeparator(' - ')->setAutoEscape(false) ?>
	
	<!-- Stylesheets -->
	<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700&subset=latin,latin-ext' rel='stylesheet'>
	<link rel="stylesheet" href="css/style.css">
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon(2).ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')?>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/script.js')
     ;
        
        ?>
        
	<!-- Optimize for mobile devices -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>  
        
    </head>
<body>    
           
<!-- TOP BAR -->
	<div id="top-bar">
		
		<div class="page-full-width">
		
			<a href="#" class="round button dark ic-left-arrow image-left "><?php echo $this->translate('Powrót na stronę główną') ?></a>

		</div> <!-- end full-width -->	
	
	</div> <!-- end top-bar -->
	
	
	
	<!-- HEADER -->
	<div id="header">
		
		<div class="page-full-width cf">
	
			<div id="login-intro" class="fl">
			
				<h1><?php echo $this->title ?></h1>
				<h5><?php echo $this->undertitle ?></h5>
                                
			</div> <!-- login-intro -->
			
			<!-- Change this image to your own company's logo -->
			<!-- The logo will automatically be resized to 39px height. -->
			<a href="#" id="company-branding" class="fr"><img src="img/rabatem.jpg" alt="Rabatem" /></a>
			
		</div> <!-- end full-width -->	

	</div> <!-- end header -->
        
        <!-- MAIN CONTENT -->
	<div id="content">
<?php echo $this->content; ?>
          <!-- /container -->
        <?php echo $this->inlineScript() ?>
          
          </div> <!-- end content -->
	
