
				<div class="content-module">
				
					<div class="content-module-heading cf">
					
						<h3 class="fl"><?php echo $this->translate('Dodaj ofertę') ?></h3>
						<span class="fr expand-collapse-text"><?php echo $this->translate('Schowaj') ?></span>
						<span class="fr expand-collapse-text initial-expand"><?php echo $this->translate('Wysuń') ?></span>
					
					</div> <!-- end content-module-heading -->
					
					
					<div class="content-module-main">
                                            <h2 class="title">Oferta została dodana</h2>
                                            <h3>Dodawanie oferty zakończyło się sukcesem</h3>
                                            
                                            Twoja oferta czeka na akceptacje w innych miastach. W miastach zarządzanych przez <strong><?php echo $this->zfcUserDisplayName() ?></strong> będzie wyświetlana od razu. 
                                            </br></br>Możesz przejść do następnych czynności związanych z tą ofertą.
					
					</div> <!-- end content-module-main -->
				
				</div> <!-- end content-module -->
				
			

			